### ISSUE TITLE
Op-node not starting up...application failed

### ISSUE THREAD

**Issue by voltagebots** [smartcontracts/simple-optimism-node#101]
when i run the docker-compose file for **goerli** testnet, op-node shows the error below

```
2023-10-25 08:07:24.043 | t=2023-10-25T07:07:24+0000 lvl=info msg="Initializing Rollup Node" |  
-- | -- | --
  |   | 2023-10-25 08:06:23.499 | t=2023-10-25T07:06:23+0000 lvl=crit msg="Application failed"                 message="incorrect L2 RPC chain id, expected from config 420, obtained from client 5" |  
  |   | 2023-10-25 08:06:23.499 | t=2023-10-25T07:06:23+0000 lvl=eror msg="Unable to create the rollup node"   error="incorrect L2 RPC chain id, expected from config 420, obtained from client 5" |  
  |   | 2023-10-25 08:06:23.499 | t=2023-10-25T07:06:23+0000 lvl=eror msg="Error initializing the rollup node" err="incorrect L2 RPC chain id, expected from config 420, obtained from client 5"

```

**Comment by voltagebots** [comment]
here is my config:
cc: @smartcontracts please assist

```
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.1.0
    container_name: op-node
    hostname: op-node
    restart: always
    command: op-node --l1= https://endpoints.omniatech.io/v1/op/goerli/public  --l1.rpckind=any --l2=http://op-geth:8551 --l1.trustrpc --network=goerli --metrics.addr=0.0.0.0 --metrics.enabled --metrics.port=7300 --rpc.addr=0.0.0.0 --rpc.port=9545 --l2.jwt-secret=/var/jwt.txt
    ports:
      - 9003:9003
      - 9545:9545
    volumes:
      - /mnt/disks/optimism/jwt.txt:/var/jwt.txt
    user: '0'
```
